services:
  prod-db: 
    image: postgres:13 
    container_name: prod-db
    ports: 
      - 5436:5432 
    env_file:
      - .env.prod
    volumes:
      - pgdata:/var/lib/postgresql/data  
    networks: 
      - coderoom

  prod-server:
    container_name: prod-server
    build:
      context: .
      dockerfile: Dockerfile
    image: coderoom-backend:1.0.0
    ports: 
      - 8080:8080 
    env_file:
      - .env.prod
    networks:
      - coderoom
    depends_on:
      - prod-db 

networks:
  coderoom:
    external: true

volumes:
  pgdata: