services: 
  dev-db: 
    image: postgres:13
    ports: 
      - 5434:5432
    env_file:
      - .env
    networks: 
      - virgo
  test-db: 
    image: postgres:13
    ports: 
      - 5435:5432
    env_file:
      - .env.test
    networks: 
      - virgo
networks:
  virgo:  