services:
  prod-server:
    image: coderoom-backend:1.0.0
    container_name: prod-server
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8080:8080 
    env_file:
      - .env.prod
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - virgo
      
networks:
  virgo: 